### ISSUE TITLE
Datepicker bug

### ISSUE THREAD

**Issue by marthesselink** [trendwerk/gravity-forms-styling#5]
When you add a datepicker to your page, a weird white block appears at the top of your page.
After clicking the date picker, it disappears.

Possible Fix:
../components/gfs-datepicker.scss 

Line 6: 
`.ui-datepicker { 
display: none;
}`

**Comment by luukdv** [comment]
Thanks, will look into it.

Reference: https://github.com/trendwerk/gravity-forms-styling/blob/master/src/components/gfs-datepicker.scss#L6

**Comment by luukdv** [comment]
Can't reproduce this one, maybe your theme is the cause?

**Comment by marthesselink** [comment]
Probably JS error on my side
